### ISSUE TITLE
Problem in paging.c, iterate_table label is never used

### ISSUE THREAD

**Issue by antlilja** [antlilja/plusplus-os#27]
After activating warnings on clang I discovered that this label is never used:
https://github.com/antlilja/plusplus-os/blob/ef3d7f5008e6364dfcdf2a0428d221adab5e1dea/kernel/src/paging.c#L176

It might point to some bug in the ```rec_setpage``` function

@eim64

**Comment by eim64** [comment]
This label was used before overwritten pagetables were freed.
It has been replaced with a comment.
